### ISSUE TITLE
Dockerfile.Centos7 fails with missing dependencies

### ISSUE THREAD

**Issue by cyberxml** [kamailio/kamailio-tests#12]
My first time attempting build of kamailio-test, so possible PEBKAC issues, but there were several missing dependencies when I attempted to create a docker build from the kamailio-tests/docker/Dockerfile.centos7 file. Corrective action was to add the following yum packages to 'step 3'

- python3-devel
- ruby-devel 
- mosquitto-devel 
- libmnl-devel

Attaching the modified Dockerfile which completed the build (apparently) successfully.

[Dockerfile.centos7.txt](https://github.com/kamailio/kamailio-tests/files/5882695/Dockerfile.centos7.txt)

**Comment by miconda** [comment]
Might be the dependencies needed by the new modules.

Can you make a pull request with the changes to the dockerfile?

It is easier to review here on the web portal and if all ok, then just merge. Thanks!

**Comment by giavac** [comment]
I've verified those changes against master kamailio and looked good - just to confirm before the PR.

**Comment by miconda** [comment]
@giavac - if you checked and get the time for it, you can also push the changes, no need to wait for PR -- I didn't have access to a system to compare the file attached and see what was changed.

**Comment by miconda** [comment]
PR made by @giavac was merged.
